from sqlalchemy import Column, Integer, String, Text, ForeignKey, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship

Base = declarative_base()

class Student(Base):
    __tablename__ = 'students'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    # Key for personalization
    preferred_learning_style = Column(String) # e.g., 'Visual', 'Auditory', 'Kinesthetic'
    known_barriers = Column(Text) # e.g., 'Dyslexia, Attention Difficulties'
    interests = Column(Text) # e.g., 'Dinosaurs, Space, Video Games'
    
    lessons = relationship("Lesson", back_populates="student")

class Lesson(Base):
    __tablename__ = 'lessons'
    id = Column(Integer, primary_key=True)
    student_id = Column(Integer, ForeignKey('students.id'))
    topic = Column(String, nullable=False)
    content = Column(Text) # The lesson content generated by the AI
    date_generated = Column(String) # Simple date/time stamp
    
    student = relationship("Student", back_populates="lessons")

# You might add a 'Feedback' or 'Progress' table later for true adaptive learning