from sqlalchemy import Column, Integer, String, Text, ForeignKey
from sqlalchemy.orm import declarative_base, relationship

# Base class which stores a catalog of classes and mapped tables
Base = declarative_base()

class Student(Base):
    """
    Represents a neurodiverse student profile for lesson personalization.
    """
    __tablename__ = 'students'
    
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    
    # Key personalization fields
    preferred_learning_style = Column(String) # e.g., 'Visual', 'Auditory', 'Kinesthetic'
    known_barriers = Column(Text) # e.g., 'Dyslexia, Attention Difficulties'
    interests = Column(Text) # e.g., 'Dinosaurs, Space, Video Games'
    
    # Relationship to lessons created for this student
    lessons = relationship("Lesson", back_populates="student", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Student(name='{self.name}', style='{self.preferred_learning_style}')>"

class Lesson(Base):
    """
    Represents a lesson generated by the AI for a specific student.
    """
    __tablename__ = 'lessons'
    
    id = Column(Integer, primary_key=True)
    student_id = Column(Integer, ForeignKey('students.id'))
    topic = Column(String, nullable=False)
    content = Column(Text) # The generated markdown lesson content
    date_generated = Column(String) # Simple date/time string
    
    # Relationship back to the student
    student = relationship("Student", back_populates="lessons")

    def __repr__(self):
        return f"<Lesson(topic='{self.topic}', date='{self.date_generated}')>"

#